// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYqzsZP7rxjE79D8V0AZWlWgt8x7fUSOw',
    appId: '1:24208070412:web:e55fab8c32fb0a6065db29',
    messagingSenderId: '24208070412',
    projectId: 'ecoglam-373a4',
    authDomain: 'ecoglam-373a4.firebaseapp.com',
    storageBucket: 'ecoglam-373a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfkfxaS-KN9FONfXBgUZ7q9v6mDZDuAQc',
    appId: '1:24208070412:android:ad4079d07ed66f3865db29',
    messagingSenderId: '24208070412',
    projectId: 'ecoglam-373a4',
    storageBucket: 'ecoglam-373a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq4tsOVeGgLJ2Z4EMKZJrgYcG5ARvo428',
    appId: '1:24208070412:ios:544d5b6f9ff6e1ea65db29',
    messagingSenderId: '24208070412',
    projectId: 'ecoglam-373a4',
    storageBucket: 'ecoglam-373a4.firebasestorage.app',
    iosBundleId: 'com.example.ecoglam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq4tsOVeGgLJ2Z4EMKZJrgYcG5ARvo428',
    appId: '1:24208070412:ios:544d5b6f9ff6e1ea65db29',
    messagingSenderId: '24208070412',
    projectId: 'ecoglam-373a4',
    storageBucket: 'ecoglam-373a4.firebasestorage.app',
    iosBundleId: 'com.example.ecoglam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYqzsZP7rxjE79D8V0AZWlWgt8x7fUSOw',
    appId: '1:24208070412:web:2fcf9b357d7aad7b65db29',
    messagingSenderId: '24208070412',
    projectId: 'ecoglam-373a4',
    authDomain: 'ecoglam-373a4.firebaseapp.com',
    storageBucket: 'ecoglam-373a4.firebasestorage.app',
  );
}
